# Generated by Django 3.2.2 on 2023-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhero',
            name='img',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
