# Generated by Django 3.2.2 on 2023-04-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание'), ('Аванс', 'Аванс')], default='Ожидание', max_length=120),
        ),
    ]
