# Generated by Django 4.0.2 on 2022-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_clients_form_alter_clients_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Ожиданы', 'Ожиданы'), ('Встреча', 'Встреча'), ('Архив', 'Архив'), ('Договор', 'Договор')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Аванс', 'Аванс'), ('Оплачено', 'Оплачено')], default='Ожидание', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectservice',
            name='parcent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
