# Generated by Django 4.0.2 on 2022-08-23 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_clients_form_alter_clients_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Ожиданы', 'Ожиданы'), ('Договор', 'Договор'), ('Архив', 'Архив')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Аванс', 'Аванс'), ('Оплачено', 'Оплачено')], default='Ожидание', max_length=120),
        ),
    ]
