# Generated by Django 4.0.2 on 2022-10-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_clients_status_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfield',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.orders'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Архив', 'Архив'), ('Договор', 'Договор'), ('Ожиданы', 'Ожиданы')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание'), ('Аванс', 'Аванс')], default='Ожидание', max_length=120),
        ),
    ]
