# Generated by Django 4.0.2 on 2022-10-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_orderfield_order_alter_clients_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfield',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_filed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.orderfield'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Ожиданы', 'Ожиданы'), ('Договор', 'Договор'), ('Архив', 'Архив'), ('Встреча', 'Встреча')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Аванс', 'Аванс'), ('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание')], default='Ожидание', max_length=120),
        ),
    ]
