# Generated by Django 4.0.2 on 2022-10-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_remove_orderfield_order_orders_order_filed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_filed',
        ),
        migrations.AddField(
            model_name='orderfield',
            name='order_filed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Оплачено', 'Оплачено'), ('Аванс', 'Аванс')], default='Ожидание', max_length=120),
        ),
    ]
