# Generated by Django 4.0.2 on 2022-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_remove_orders_order_filed_orderfield_order_filed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Ожиданы', 'Ожиданы'), ('Архив', 'Архив'), ('Встреча', 'Встреча'), ('Договор', 'Договор')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оплачено', 'Оплачено'), ('Ожидание', 'Ожидание'), ('Аванс', 'Аванс')], default='Ожидание', max_length=120),
        ),
    ]
