# Generated by Django 3.2.2 on 2023-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20230324_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Встреча', 'Встреча'), ('Ожиданы', 'Ожиданы'), ('Архив', 'Архив'), ('Договор', 'Договор')], default='Ожиданы', max_length=120, null=True),
        ),
    ]
