# Generated by Django 3.2.2 on 2023-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('Ожиданы', 'Ожиданы'), ('Встреча', 'Встреча'), ('Договор', 'Договор'), ('Архив', 'Архив')], default='Ожиданы', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Аванс', 'Аванс'), ('Оплачено', 'Оплачено')], default='Ожидание', max_length=120),
        ),
    ]
