# Generated by Django 3.2.18 on 2023-04-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20230401_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='form',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.ForeignKey(blank=True, default='Ожиданы', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.clientsstatus'),
        ),
    ]
